sonar.projectKey=python-practice
sonar.projectName=Python Practice
sonar.sources=calculator.py
sonar.tests=test_calculator.py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
